# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: ./.github/workflows/reusable-integration-test.yml
    strategy:
      matrix:
        site:
        - { id: 60f6ec0bd28860bc3384daa1, host: athleticbusiness.com }
        - { id: 60f6ec3bd28860bc3384e784, host: woodfloorbusiness.com }
        - { id: 60f6ec34d28860bc3384e447, host: aquamagazine.com }
    with:
      docker_image: website-${{ matrix.site.host }}
      site_id: ${{ matrix.site.id }}
      site_host: ${{ matrix.site.host }}
      infra_stack: virgon
