# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration Tests

env:
  ab: fromJson(vars.SITE_AB)

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: ./.github/workflows/reusable-integration-test.yml
    strategy:
      matrix:
        site: ${{ fromJSON(vars.SITES_CONFIG) }}
          # - { id: "${{ fromJson(vars.SITE_AB).id }}", host: "${{ fromJson(vars.SITE_AB).host }}" }
        # - fromJson(${{ vars.SITE_AQUA }})
        # - fromJson(${{ vars.SITE_WFB }})
    with:
      docker_image: website-${{ matrix.site.host }}
      site_id: ${{ matrix.site.id }}
      site_host: ${{ matrix.site.host }}
      infra_stack: virgon
