name: Integration test

on:
  workflow_call:
    inputs:
      docker_image:
        type: string
        required: true
      site_host:
        type: string
        required: true
      site_id:
        type: string
        required: true
      infra_stack:
        type: string
        required: true
      push:
        type: boolean
        default: false
      ecr_registry:
        type: string
        required: true
      tenant_key:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to ECR
        if: inputs.push
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.ecr_registry }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ inputs.push }}
          build-args: |
            SITE=${{ inputs.site_host }}
          tags: ${{ inputs.docker_image }}

      - name: Boot docker image
        run: |
          docker run -p 80:80 \
            --name website-${{ inputs.site_host }} \
            -e TENANT_KEY=${{ inputs.tenant_key }} \
            -e SITE_ID=${{ inputs.site_id }} \
            -e GRAPHQL_URI=https://graphql.${{ inputs.infra_stack }}.base.parameter1.com \
            -e OEMBED_URI=https://oembed.${{ inputs.infra_stack }}.base.parameter1.com \
            -e RSS_URI=https://rss.${{ inputs.infra_stack }}.base.parameter1.com \
            -e SITEMAPS_URI=https://sitemaps.${{ inputs.infra_stack }}.base.parameter1.com \
            -e RECAPTCHA_V3_SITE_KEY=not-set \
            -e RECAPTCHA_V3_SECRET_KEY=not-set \
            -e SENDGRID_API_KEY=not-set \
            -e OMEDA_APP_ID=not-set \
            -e OMEDA_INPUT_ID=not-set \
            ${{ inputs.docker_image }} &

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run integration tests
        run: node ./test/integration.js
        timeout-minutes: 1

      - name: Stop docker image
        run: docker stop website-${{ inputs.site_host }}
